name: Fork Sync
on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:
  
env:
  LAST_VERSION: v2022.1.1

jobs:
  get-latest:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest-tag.outputs.tag }}
    steps:
      - run: echo '::echo::on'
      - name: Get Latest WPILibPi Tag
        id: latest-tag
        run: echo "::set-output name=tag::$(curl -s https://api.github.com/repos/wpilibsuite/WPILibPi/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Confirm Version
        run: |
          echo "${{ steps.latest-tag.outputs.tag }}"
          echo "${{ env.LAST_VERSION != steps.latest-tag.outputs.tag }}"
        
  update:
    needs: get-latest
    if: needs.get-latest.outputs.latest-tag != 'v2022.1.1'
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.WORKFLOW_ACCESS }}
      - run: |
          sed -i '0,/^.*LAST_VERSION:.*/s//  LAST_VERSION: ${{ needs.get-latest.outputs.latest-tag }}/' ./.github/workflows/sync.yml
          sed -i "0,/^.*if: needs.get-latest.outputs.latest-tag !=.*/s//    if: needs.get-latest.outputs.latest-tag != '${{ needs.get-latest.outputs.latest-tag }}'/" ./.github/workflows/sync.yml
          cat ./.github/workflows/sync.yml
      - uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: ${{ env.LAST_VERSION }} --> ${{ needs.get-latest.outputs.latest-tag }}
          tagging_message: ${{ needs.get-latest.outputs.latest-tag }}
          
  alternate:
    needs: get-latest
    if: needs.get-latest.outputs.latest-tag == 'v2021.4.1'
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.WORKFLOW_ACCESS }}
      - run: |
          sed -i '0,/^.*LAST_VERSION:.*/s//  LAST_VERSION: ${{ needs.get-latest.outputs.latest-tag }}/' ./.github/workflows/sync.yml
          sed -i "0,/^.*if: needs.get-latest.outputs.latest-tag !=.*/s//    if: needs.get-latest.outputs.latest-tag != '${{ needs.get-latest.outputs.latest-tag }}'/" ./.github/workflows/sync.yml
          cat ./.github/workflows/sync.yml
#      - uses: stefanzweifel/git-auto-commit-action@master
#        with:
#          commit_message: ${{ env.LAST_VERSION }} --> ${{ needs.get-latest.outputs.latest-tag }} (test)
#          tagging_message: ${{ needs.get-latest.outputs.latest-tag }}

  sync:
    needs: [get-latest, update]
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - uses: aormsby/Fork-Sync-With-Upstream-action@master
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: wpilibsuite/WPILibPi
          upstream_sync_branch: main
