name: Fork Sync
on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:
  
env:
  LAST_VERSION: v2022.1.1

jobs:
  get-latest:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest-tag.outputs.tag }}
    steps:
      - run: echo '::echo::on'
      - name: Get Latest WPILibPi Tag
        id: latest-tag
        run: echo "::set-output name=tag::$(curl -s https://api.github.com/repos/wpilibsuite/WPILibPi/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Confirm Version
        run: |
          echo "${{ steps.latest-tag.outputs.tag }}"
          echo "${{ env.LAST_VERSION != steps.latest-tag.outputs.tag }}"
        
  sync:
    needs: get-latest
    if: needs.get-latest.outputs.latest-tag != 'v2022.1.1'
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: |
          sed -i 's/^.*LAST_VERSION:.*/\tLAST_VERSION: ${{ needs.get-latest.outputs.latest-tag }}/' ./.github/workflows/sync.yml
          sed -i 's/^.*if: needs.get-latest.outputs.latest-tag !=.*/\t\tif: needs.get-latest.outputs.latest-tag != #{{ needs.get-latest.outputs.latest-tag }}/' ./.github/workflows/sync.yml
          cat ./.github/workflows/sync.yml
          
  alternate:
    needs: get-latest
    if: needs.get-latest.outputs.latest-tag == 'v2022.1.1'
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: |
          sed -i '0,/^.*LAST_VERSION:.*/s//\tLAST_VERSION: ${{ needs.get-latest.outputs.latest-tag }}/' ./.github/workflows/sync.yml
          sed -i '0,/^.*if: needs.get-latest.outputs.latest-tag !=.*/s//\t\tif: needs.get-latest.outputs.latest-tag != #{{ needs.get-latest.outputs.latest-tag }}/' ./.github/workflows/sync.yml
          cat ./.github/workflows/sync.yml
